const FIREBASE_API_KEY = 'AIzaSyAMeF1Z5syis6vDTyHQtJ44Qh3_bGB2Gps';
const FIREBASE_AUTH_DOMAIN = 'letsmeet-a3cbe.firebaseapp.com';
const FIREBASE_DATABASE_URL = 'https://letsmeet-a3cbe.firebaseio.com';
const FIREBASE_PROJECT_ID = 'letsmeet-a3cbe';
const FIREBASE_STORAGE_BUCKET = 'letsmeet-a3cbe.appspot.com';
const FIREBASE_MESSAGING_SENDER_ID = '472038597943';

const GOOGLE_MAPS_API_KEY = 'AIzaSyAd3KucV9ap_X0cJmIHl37P4Hw0VI9eHQQ';
const GOOGLE_MAPS_PLACE_API_KEY = 'AIzaSyAOkeHdz33iLnUmkyWmoFoZ_B0otaz7ISY';

const DATE_FORMAT = 'MMMM Do YYYY, h:mm a';

const MORNING_START = '06:00';
const AFTERNOON_START = '12:00';
const NIGHT_START = '18:00';
const LATENIGHT_START = '00:00';


module.exports = {
    FIREBASE_API_KEY: FIREBASE_API_KEY,
    FIREBASE_AUTH_DOMAIN: FIREBASE_AUTH_DOMAIN,
    FIREBASE_DATABASE_URL: FIREBASE_DATABASE_URL,
    FIREBASE_PROJECT_ID: FIREBASE_PROJECT_ID,
    FIREBASE_STORAGE_BUCKET: FIREBASE_STORAGE_BUCKET,
    FIREBASE_MESSAGING_SENDER_ID: FIREBASE_MESSAGING_SENDER_ID,
    GOOGLE_MAPS_API_KEY: GOOGLE_MAPS_API_KEY,
    GOOGLE_MAPS_PLACE_API_KEY: GOOGLE_MAPS_PLACE_API_KEY,
    DATE_FORMAT: DATE_FORMAT,
    MORNING_START: MORNING_START,
    AFTERNOON_START: AFTERNOON_START,
    NIGHT_START: NIGHT_START,
    LATENIGHT_START: LATENIGHT_START
};